language: php
php:
  - nightly
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_script:
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover=coverage/coverage.xml --configuration=tests/phpunit.xml

after_script:
  - php vendor/bin/coveralls

matrix:
  allow_failures:
    - php: nightly
    - php: 7.0
